version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
    build:
      docker:
        - image: circleci/ruby
    steps:
      - checkout
      - run:
        name: install jekyll
        command: gem install bundler
        command: bundle install
