version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install bundler
          command: 'gem install bundler'
      - run:
          name: run bundler install
          command: 'cd ~/blog/jekyll-uno && bundle install'
      - run:
          name: build site
          command: 'cd ~/blog/jekyll-uno && jekyll build'
      - run:
          name: create artefact
          command: 'tar -cvf ~/blog/build.tar ~/blog/jekyll-uno/_site'
      - store_artifacts:
          path: '~/blog/build.tar'
      - save_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/blog/jekyll-uno/_site/

  cert:
    working_directory: ~/blog
    docker:
      - image: certbot/dns-route53
    steps:
      - checkout
      - run:
          name: Add AWS CLI
          command: 'pip install awscli'
      - run:
          name: Renew Cert
          command: 'sh ~/blog/letsencrypt/cert.sh'
          environment:
            DOMAIN: 'armstro.ca'
            CERTDATAFILE: 'certData'
      - persist_to_workspace:
          root: .
          paths:
            - certData

  environment:
    working_directory: ~/blog
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: initiate terraform
          command: 'cd terraform && terraform init -backend-config=armstro.ca.backend.tfvars -reconfigure -no-color -input=false'
      - attach_workspace:
          at: .
      - run:
          name: grep certId
          command: eval "export certId=`cat certData | grep ServerCertificateId | awk -F'[:]' '{print $2}' | cut -c3-23`"
      - run:
          name: apply terraform
          command: eval "cd terraform && terraform apply -auto-approve -no-color -input=false -var 'certId=$certId'"

  deploy:
    docker:
      - image: circleci/python
    working_directory: ~/blog/jekyll-uno/_site/
    steps:
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      - restore_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to S3
          command: 'aws s3 sync ~/blog/jekyll-uno/_site/ s3://armstro.ca/ --delete --cache-control max-age=600'

workflows:
  version: 2
  build_jekyll:
    jobs:
      - build
      - cert
      - environment:
          requires:
            - cert
      - deploy:
          requires:
            - build
            - environment
