version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    working_directory: ~/jekyll_uno
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install bundler
          command: 'gem install bundler'
      - run:
          name: run bundler install
          command: 'bundle install'

workflows:
  version: 2
  build_jekyll:
    jobs:
      - build
