version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install bundler
          command: 'gem install bundler'
      - run:
          name: run bundler install
          command: 'cd ~/blog/jekyll-uno && bundle install'
      - run:
          name: build site
          command: 'cd ~/blog/jekyll-uno && jekyll build'
      - run:
          name: create artefact
          command: 'tar -cvf ~/blog/build.tar ~/blog/jekyll-uno/_site'
      - store_artifacts:
          path: '~/blog/build.tar'
      - save_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/blog/jekyll-uno/_site/

  environment-beta:
    working_directory: ~/blog
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: initiate terraform
          command: 'cd terraform && terraform init -backend-config=beta.armstro.co.backend.tfvars -reconfigure -no-color -input=false'
      - run:
          name: apply terraform
          command: 'cd terraform && terraform apply -auto-approve -no-color -input=false -var "domain=beta.armstro.co"'

  deploy-beta:
    docker:
      - image: circleci/python
    working_directory: ~/blog/jekyll-uno/_site/
    steps:
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      - restore_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to S3
          command: 'aws s3 sync ~/blog/jekyll-uno/_site/ s3://beta.armstro.co/ --delete --cache-control max-age=600'


  environment-prod:
    working_directory: ~/blog
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: initiate terraform
          command: 'cd terraform && terraform init -backend-config=armstro.co.backend.tfvars -reconfigure -no-color -input=false'
      - run:
          name: apply terraform
          command: 'cd terraform && terraform apply -auto-approve -no-color -input=false'

  deploy:
    docker:
      - image: circleci/python
    working_directory: ~/blog/jekyll-uno/_site/
    steps:
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      - restore_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to S3
          command: 'aws s3 sync ~/blog/jekyll-uno/_site/ s3://armstro.co/ --delete --cache-control max-age=600'

workflows:
  version: 2
  build_jekyll:
    jobs:
      - build
      - environment-beta
      - deploy-beta:
          requires:
            - build
            - environment-beta
      - approve:
          type: approval
          requires:
            - deploy-beta
          filters:
            branches:
              only: master
      - environment-prod:
          requires:
            - approve
      - deploy:
          requires:
            - approve
