version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install bundler
          command: 'gem install bundler'
      - run:
          name: run bundler install
          command: 'cd ~/blog/jekyll-uno && bundle install'
      - run:
          name: build site
          command: 'cd ~/blog/jekyll-uno && jekyll build'
      - run:
          name: create artefact
          command: 'tar -cvf ~/blog/build.tar ~/blog/jekyll-uno/_site'
      - store_artifacts:
          path: '~/blog/build.tar'
      - save_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/blog/jekyll-uno/_site/

  # uat:
  #   working_directory: ~/blog
  #   steps:
  #     - run:
  #         name: s3sync
  #         command: 'aws s3 sync jekyll-uno/_site/ s3://armstro.co/'
workflows:
  version: 2
  build_jekyll:
    jobs:
      - build
      # - uat
