version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install bundler
          command: 'gem install bundler'
      - run:
          name: location diagnostics
          command: 'pwd && ls -al'
      - run:
          name: run bundler install
          command: 'cd ~/jekyll-uno && bundle install'

workflows:
  version: 2
  build_jekyll:
    jobs:
      - build
